################################################################################
# \file bsp.mk
#
# \brief
# Define the CYW955513EVK-01 target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Additional devices on the board
#    If you change the additional device here you must also update the design.modus file and re-run
#    the device configurator. You may also need to update the COMPONENT variable to include the
#    correct Wi-Fi and Bluetooth firmware.

LIFE_CYCLE_STATE?=DM

# Any additional components to apply when using this board.
BSP_COMPONENTS:=CYW955513WLIPA

# this is need for picking the secure/non secure Firmware image
ifeq ($(LIFE_CYCLE_STATE),DM)
BSP_COMPONENTS+=SM
else
BSP_COMPONENTS+=CM
endif

BSP_DEFINES=CY_USING_HAL

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYW55513IUBG

# Device specific components picked up by pdl-cat5.mk file
DEVICE_COMPONENTS:=55500 55500A1

-include $(SEARCH_mtb-pdl-cat5)/devices/pdl-cat5.mk
DEVICE:=CYW55513IUBG
DEVICE_CYW55513IUBG_CORES:=CORE_NAME_CM33_0
DEVICE_CYW55513IUBG_DIE:=55500A1
DEVICE_CYW55513IUBG_FLASH_KB:=0
DEVICE_CYW55513IUBG_SRAM_KB:=768
DEVICE_LIST:=CYW55513IUBG
DEVICE_TOOL_IDS:=bsp-assistant bt-configurator device-configurator library-manager project-creator
RECIPE_DIR:=$(SEARCH_recipe-make-cat5)
