################################################################################
# \file bsp.mk
#
# \brief
# Define the CYW955513EVK-01 target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

#
# Device definition
#
# MCU device selection
#    Changing the device should be done using "make bsp" or "make update_bsp" with the "DEVICE_GEN"
#    variable set to the new MCU. If you change the device manually here you must also update the
#    design.modus file and re-run the device configurator.

CHIP=55500
CHIP_REV?=A0
CY_TARGET_DEVICE?=$(CHIP)$(CHIP_REV)

# Additional devices on the board
#    If you change the additional device here you must also update the design.modus file and re-run
#    the device configurator. You may also need to update the COMPONENT variable to include the
#    correct Wi-Fi and Bluetooth firmware.

LIFE_CYCLE_STATE?=DM

# Any additional components to apply when using this board.
BSP_COMPONENTS:=$(CY_TARGET_DEVICE)
# this is necessary until CAT5 is supported by bsp_assistant
BSP_COMPONENTS+=CAT5

BSP_DEFINES=CY_USING_HAL

-include $(SEARCH_mtb-pdl-cat5)/devices/pdl-cat5.mk

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYW55513IUBG
DEVICE:=CYW55513IUBG
DEVICE_TOOL_IDS:=device-configurator library-manager project-creator bt-configurator fw-loader
RECIPE_DIR=$(SEARCH_recipe-make-cat5)
